import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { Screen } from '@/components/Screen'; import { Card } from '@/components/Card'; import { Button } from '@/components/Button'; import { useTheme } from '@/providers/ThemeProvider'; import { useSchedule } from '@/hooks/useSchedule'; import { requestNotificationPermission, rescheduleCampusLifeNotifications } from '@/notifications/notification.service'; import type { DayKey, Schedule as ScheduleType } from '@/types/schedule';

const dayLabels: [DayKey, string][] = [['monday', 'Mon'], ['tuesday', 'Tue'], ['wednesday', 'Wed'], ['thursday', 'Thu'], ['friday', 'Fri'], ['saturday', 'Sat'], ['sunday', 'Sun']];
const intervals = [30, 60, 120, 180]; const warnings = [0, 15, 30, 60];
const displayTime = (value: string) => new Date(`2000-01-01T${value}:00`).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' });
const cycle = <T,>(items: T[], current: T) => items[(items.indexOf(current) + 1) % items.length];

export default function Schedule() {
  const theme = useTheme(); const { schedule, setSchedule, loading, error, save } = useSchedule(); const [saving, setSaving] = useState(false);
  const update = (next: Partial<ScheduleType>) => setSchedule({ ...schedule, ...next });
  const saveSchedule = async () => { setSaving(true); try { const saved = await save(schedule); const permissions = await requestNotificationPermission(); if (!permissions.granted) { Alert.alert('Notifications are disabled', 'Enable notifications in Settings to receive Campus Life reminders.'); return; } const result = await rescheduleCampusLifeNotifications(saved); Alert.alert('Schedule saved', `${result.scheduled} upcoming reminders have been scheduled on this phone.`); } catch (cause) { Alert.alert('Could not save schedule', cause instanceof Error ? cause.message : 'Please try again.'); } finally { setSaving(false); } };
  if (loading) return <Screen><ActivityIndicator color={theme.primary} /><Text style={[styles.loading, { color: theme.secondary }]}>Loading your schedule…</Text></Screen>;
  return <Screen><Text style={[styles.title, { color: theme.text }]}>Schedule</Text><Text style={[styles.subtitle, { color: theme.secondary }]}>Set the routine that CampusLife Buddy should watch.</Text>{error ? <Text style={[styles.error, { color: theme.secondary }]}>{error} Showing your saved-on-device defaults.</Text> : null}<Text style={[styles.heading, { color: theme.text }]}>Campus Life days</Text><Card><View style={styles.days}>{dayLabels.map(([key, label]) => <Pressable accessibilityRole="button" accessibilityLabel={`${label} ${schedule[key] ? 'selected' : 'not selected'}`} onPress={() => update({ [key]: !schedule[key] } as Partial<ScheduleType>)} key={key} style={[styles.day, { backgroundColor: schedule[key] ? theme.primary : theme.background, borderColor: theme.border }]}><Text style={{ color: schedule[key] ? theme.background : theme.text, fontWeight: '700' }}>{label}</Text></Pressable>)}</View></Card><Text style={[styles.heading, { color: theme.text }]}>Daily timing</Text><Card><Selector label="Start time" value={displayTime(schedule.startTime)} onPress={() => update({ startTime: schedule.startTime === '09:15' ? '09:30' : '09:15' })} /><Selector label="End time" value={displayTime(schedule.endTime)} onPress={() => update({ endTime: schedule.endTime === '16:45' ? '17:00' : '16:45' })} /></Card><Text style={[styles.heading, { color: theme.text }]}>Reminders</Text><Card><Selector label="Activity / photo" value={`Every ${schedule.photoIntervalMinutes < 60 ? `${schedule.photoIntervalMinutes} min` : `${schedule.photoIntervalMinutes / 60} hour${schedule.photoIntervalMinutes === 60 ? '' : 's'}`}`} onPress={() => update({ photoIntervalMinutes: cycle(intervals, schedule.photoIntervalMinutes) })} /><Selector label="Checkout warning" value={schedule.checkoutWarningMinutes ? `${schedule.checkoutWarningMinutes} minutes before` : 'Off'} onPress={() => update({ checkoutWarningMinutes: cycle(warnings, schedule.checkoutWarningMinutes) })} /><View style={styles.switchRow}><Text style={[styles.switchText, { color: theme.text }]}>Activity reminders</Text><Switch value={schedule.photoIntervalMinutes > 0} onValueChange={(enabled) => update({ photoIntervalMinutes: enabled ? 60 : 240 })} trackColor={{ false: theme.border, true: theme.primary }} /></View></Card><Card><Text style={[styles.smallLabel, { color: theme.secondary }]}>TIMEZONE</Text><Text style={[styles.timezone, { color: theme.text }]}>{schedule.timezone}</Text></Card><Button label={saving ? 'Saving…' : 'Save schedule'} onPress={() => void saveSchedule()} style={styles.save} /></Screen>;
}
function Selector({ label, value, onPress }: { label: string; value: string; onPress: () => void }) { const theme = useTheme(); return <Pressable accessibilityRole="button" accessibilityLabel={`${label}: ${value}`} onPress={onPress} style={[styles.setting, { borderColor: theme.border }]}><Text style={[styles.settingLabel, { color: theme.secondary }]}>{label}</Text><View style={styles.valueRow}><Text style={[styles.value, { color: theme.text }]}>{value}</Text><Text style={[styles.change, { color: theme.secondary }]}>Change</Text></View></Pressable>; }
const styles = StyleSheet.create({ title: { fontSize: 30, fontWeight: '800', letterSpacing: -0.7 }, subtitle: { fontSize: 16, marginTop: 7, lineHeight: 22 }, error: { marginTop: 15, fontSize: 13, lineHeight: 19 }, loading: { textAlign: 'center', marginTop: 14 }, heading: { marginTop: 29, marginBottom: 10, fontSize: 13, fontWeight: '800' }, days: { flexDirection: 'row', justifyContent: 'space-between' }, day: { width: 37, height: 37, borderWidth: 1, borderRadius: 19, alignItems: 'center', justifyContent: 'center' }, setting: { paddingVertical: 13, borderBottomWidth: StyleSheet.hairlineWidth }, settingLabel: { fontSize: 13 }, valueRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 4 }, value: { fontSize: 16, fontWeight: '700' }, change: { fontSize: 13, fontWeight: '700' }, switchRow: { paddingTop: 15, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, switchText: { fontSize: 16, fontWeight: '700' }, smallLabel: { fontWeight: '800', fontSize: 11, letterSpacing: 0.7 }, timezone: { fontSize: 17, fontWeight: '700', marginTop: 7 }, save: { marginTop: 26, marginBottom: 12 } });
